# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_date',
            new_name='upload_datetime',
        ),
        migrations.AddField(
            model_name='upload',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(default='test default', max_length=100),
            preserve_default=False,
        ),
    ]
