# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_upload', '0002_auto_20170701_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='docfile',
            field=models.FileField(upload_to='uploads/', verbose_name='Document'),
        ),
    ]
