# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_supp_shifts', '0001_initial'),
        ('app_supp_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='app_supp_teams.Team'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='app_supp_shifts.ShiftTemplate'),
        ),
        migrations.AddField(
            model_name='shift',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
