# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_teams', '0001_initial'),
        ('app_supp_shifts', '0002_auto_20170507_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplateOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=25)),
                ('shift_description', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates_old', to='app_supp_teams.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='active',
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='fri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='mon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='sat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='sun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='thu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='tue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='wed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
