# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_shifts', '0003_auto_20170521_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='sun',
            field=models.BooleanField(default=False),
        ),
    ]
