# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_shifts', '0004_auto_20170618_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplateold',
            name='team',
        ),
        migrations.DeleteModel(
            name='ShiftTemplateOld',
        ),
    ]
