# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_shifts', '0006_shifttemplate_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='repeat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
