# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_supp_calendar', '0001_initial'),
        ('app_supp_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='app_supp_teams.Team'),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='app_supp_calendar.Year'),
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app_supp_calendar.Month'),
        ),
    ]
