# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_calendar', '0002_auto_20170507_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='month',
        ),
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='team',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
