# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_users', '0002_auto_20170521_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='app_supp_teams.Team'),
        ),
    ]
