# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_users', '0003_auto_20170605_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_shift',
        ),
    ]
