# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_users', '0005_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Management',
        ),
    ]
