# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_supp_shifts', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('default_shift_templates', models.ManyToManyField(blank=True, related_name='default_shifts', to='app_supp_shifts.ShiftTemplate')),
                ('team_manager_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manger_group', to='auth.Group')),
                ('team_member_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_group', to='auth.Group')),
            ],
        ),
    ]
