# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('app_supp_teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_manager_group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_member_group',
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_group_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
