# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_teams', '0002_auto_20170521_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager_group_name',
            field=models.CharField(default='No Name Set', max_length=60),
        ),
    ]
