# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_teams', '0006_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invite_message',
            field=models.CharField(default='Team Invite', max_length=250),
        ),
    ]
