# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_supp_teams', '0005_remove_team_manager_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('created_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='unknown', max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('affected_party', models.CharField(max_length=50)),
                ('affected_department', models.CharField(default='unknown', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app_supp_teams.Team')),
            ],
        ),
    ]
