# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='last_modified',
            new_name='sla_date',
        ),
    ]
