# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_tickets', '0003_auto_20170701_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
