# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supp_tickets', '0004_auto_20170701_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
